<?php
error_reporting();

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://zilstream.com/_next/data/6Sbk0EDtlZVcGEYX82geQ/tokens/port.json?symbol=port');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Authority: zilstream.com';
$headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Microsoft Edge\";v=\"90\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46';
$headers[] = 'Accept: */*';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: cors';
$headers[] = 'Sec-Fetch-Dest: empty';
$headers[] = 'Referer: https://zilstream.com/';
$headers[] = 'Accept-Language: en-US,en;q=0.9';
$headers[] = 'Cookie: __cfduid=dfed520bc5e0e08a67a79611029867a7e1619441484';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$a = json_decode($result, TRUE);
$name = $a["pageProps"]["token"]["name"];
$simbol = $a["pageProps"]["token"]["symbol"];
$rateZil = $a["pageProps"]["token"]["rate"];
$rateUsd = $a["pageProps"]["token"]["rate_usd"];
$change = $a["pageProps"]["token"]["market_data"]["change_percentage_24h"];
$marketCap = $a["pageProps"]["token"]["market_cap"];
$volume = $a["pageProps"]["token"]["daily_volume"];
$cirSupply = $a["pageProps"]["token"]["current_supply"];


?>